# Generated by Django 6.0.7 on 2026-07-25 20:55

import students.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=students.utils.get_student_media_path_prefix),
        ),
    ]
