# Generated by Django 6.0.7 on 2026-08-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_task_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdraft',
            name='missing_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
