# Generated by Django 6.0.7 on 2026-08-09 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_applicationdraft_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('DOCUMENTS_PENDING', 'Documents Pending'), ('SHORTLISTED', 'Shortlisted'), ('PREPARED', 'Prepared'), ('SUBMITTED', 'Submitted'), ('ENROLLED', 'Enrolled')], max_length=50)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='students.case')),
            ],
            options={
                'ordering': ['entered_at'],
            },
        ),
    ]
