# Generated by Django 6.0.7 on 2026-07-28 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('unmet_requirements', models.JSONField(blank=True, default=list)),
                ('recommendation_notes', models.TextField(blank=True)),
                ('risk_notes', models.TextField(blank=True)),
                ('adviser_override_reason', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('campus', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('intake_dates', models.JSONField(blank=True, default=list)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('academic_requirements', models.TextField(blank=True)),
                ('english_requirements', models.TextField(blank=True)),
                ('prerequisite_requirements', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('last_verification_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_partner_provider', models.BooleanField(default=False)),
                ('commission_notes', models.TextField(blank=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
