# Generated by Django 6.0.7 on 2026-07-25 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_category', models.CharField(choices=[('IDENTITY', 'Identity'), ('ACADEMIC', 'Academic'), ('ENGLISH', 'English'), ('FINANCIAL', 'Financial'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('TRANSCRIPT', 'Transcript'), ('O_LEVEL', 'O Level'), ('A_LEVEL', 'A Level'), ('ENGLISH_RESULT', 'English Result'), ('POLICE_CLEARANCE', 'Police Clearance'), ('FINANCIAL', 'Financial'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('doc_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('original_file', models.FileField(upload_to='documents/originals/')),
                ('renamed_file', models.FileField(blank=True, null=True, upload_to='documents/renamed/')),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.case')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'DRAFT'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=255)),
                ('extracted_value', models.TextField()),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('confidence_value', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='documents.document')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
