# Generated by Django 6.0.7 on 2026-07-25 20:55

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organisation_user_organisation_organisationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.get_user_media_path_prefix),
        ),
    ]
