# Generated by Django 6.0.7 on 2026-08-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsettings',
            name='data_retention_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
